// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransportApi.Infra.Context;

#nullable disable

namespace TransportApi.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransportApi.Domain.Entities.Transport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusTransport")
                        .HasColumnType("integer");

                    b.Property<int>("TypeTransport")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Transports", (string)null);

                    b.HasDiscriminator<int>("TypeTransport");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TransportApi.Domain.Entities.Airplane", b =>
                {
                    b.HasBaseType("TransportApi.Domain.Entities.Transport");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("TransportApi.Domain.Entities.Car", b =>
                {
                    b.HasBaseType("TransportApi.Domain.Entities.Transport");

                    b.HasDiscriminator().HasValue(1);
                });
#pragma warning restore 612, 618
        }
    }
}
